services:
  comfyui-worker:
    image: blacktailai/blacktail-comfyui-worker:latest # Change to your image name
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - SERVE_API_LOCALLY=true
      # Add any other environment variables you need for testing
      # - BUCKET_ENDPOINT_URL=your-s3-endpoint
      # - BUCKET_ACCESS_KEY_ID=your-access-key
      # - BUCKET_SECRET_ACCESS_KEY=your-secret-key
    ports:
      - "8000:8000" # Worker API
      - "8188:8188" # ComfyUI interface
    volumes:
      - ./data/comfyui/output:/comfyui/output
      - ./data/runpod-volume:/runpod-volume
