name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  release:
    types: [published]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/build-push-action@v3

      - name: Set Docker Tags
        id: tags
        run: |
          if [[ "${{ github.event_name }}" == "release" ]]; then
            # For releases: tag with release version and latest
            echo "tags=${{ secrets.DOCKERHUB_USERNAME }}/blacktail-comfyui-worker:${{ github.event.release.tag_name }},${{ secrets.DOCKERHUB_USERNAME }}/blacktail-comfyui-worker:latest" >> $GITHUB_OUTPUT
          else
            # For main branch pushes: tag with commit SHA and dev
            echo "tags=${{ secrets.DOCKERHUB_USERNAME }}/blacktail-comfyui-worker:${{ github.sha }},${{ secrets.DOCKERHUB_USERNAME }}/blacktail-comfyui-worker:dev" >> $GITHUB_OUTPUT
          fi

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.tags.outputs.tags }}
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max